CREATE TABLE files (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ttl BIGINT(20) NOT NULL,
  shortUrl varchar(255),
  asyncKey VARCHAR(255),
  hmac VARBINARY(32),
  _salt VARBINARY(32),
  created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE file_chunks (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fileId INT(11) NOT NULL,
  _order INT(11) NOT NULL,
  s3Path VARCHAR(255) NOT NULL,
  md5 VARBINARY(32),
  created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE basic_analytics (
  id INT(11) NOT NULL AUTO_INCREMENT,
  field_name VARCHAR(255) NOT NULL,
  int_value INT(11) NOT NULL,
  created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;