ALTER TABLE files ADD uploadUrl VARCHAR(1024) NOT NULL;
ALTER TABLE files ADD aData VARCHAR(255) NOT NULL;
ALTER TABLE files ADD iv VARCHAR(255) NOT NULL;
ALTER TABLE files ADD _salt VARCHAR(255) NOT NULL;