TRUNCATE TABLE files;
ALTER TABLE files CHANGE COLUMN iv iv VARBINARY(12) NOT NULL;
ALTER TABLE files CHANGE COLUMN aData aData VARBINARY(12) NOT NULL;
ALTER TABLE files CHANGE COLUMN _salt _salt VARBINARY(32) NOT NULL;