TRUNCATE TABLE files;
ALTER TABLE files CHANGE COLUMN iv iv  VARCHAR(255) NOT NULL;
ALTER TABLE files CHANGE COLUMN aData aData VARCHAR(255) NOT NULL;
ALTER TABLE files CHANGE COLUMN _salt _salt VARCHAR(255) NOT NULL;