CREATE TABLE file_chunks (
  id INT NOT NULL AUTO_INCREMENT,
  fileId INT NOT NULL,
  _size INT NOT NULL,
  _order INT NOT NULL,
  s3Path VARCHAR(255) NOT NULL,
  created DATETIME NOT NULL DEFAULT,
  PRIMARY KEY (id)
  ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

ALTER TABLE files DROP s3Path;
ALTER TABLE files DROP uploadUrl;
